SELECT
    CI.ESTAB,
    CI.IDCARRINHO,
    CI.SEQITEM,
    CI.IDITEM || ' - ' || I.DESCRICAO AS PRODUTO,
    CI.QUANTIDADE,
    CI.VALORUNIT,
    CI.DESCITEM + CI.DESCONTO AS DESCONTO,
    CI.CUSTOAQUIS,
    CI.VALORC,
    CI.PRECONORMALORI,
    CI.PRECOPROMOORI,
    CI.CUSTOMEDIO,
    CI.PMZ,
    CI.DETALHECALCPMZ,
    ROUND(CASE WHEN (CI.QUANTIDADE * CI.VALORUNIT) > 0
      THEN DIVIDE((COALESCE(CI.DESCITEM,0) * 100), (CI.QUANTIDADE * CI.VALORUNIT)) 
      ELSE 0    
    END,4) DESCITEMPERC,
    CI.DESCMAX,
    CASE
      WHEN COALESCE(CI.ICMSCST, '') = '' THEN 
        COALESCE(IP.PERCICMS, 0) + COALESCE(IP.PERCPIS, 0) + COALESCE(IP.PERCCOFINS, 0) 
      ELSE COALESCE(CI.ICMSALIQ, 0) + COALESCE(CI.PISALIQ, 0) + COALESCE(CI.COFINSALIQ, 0) + COALESCE(CI.ISSALIQ,0)
    END  IMPOSTOS,
    ARREDONDAR(DIVIDE(C.JUROS *((CI.QUANTIDADE * CI.VALORUNIT) - NVL(CI.DESCITEM,0) ),
    SUM((CI.QUANTIDADE * CI.VALORUNIT) - NVL(CI.DESCITEM,0)) OVER (PARTITION BY CI.IDCARRINHO)),DECODE(FV.JUROSNOPROD,'S',6,2)) JUROS,  
    ARREDONDAR(DIVIDE(C.DESPESAS*((CI.QUANTIDADE * CI.VALORUNIT) - NVL(CI.DESCITEM,0) ),
      SUM((CI.QUANTIDADE * CI.VALORUNIT) - NVL(CI.DESCITEM,0)) OVER (PARTITION BY CI.IDCARRINHO)),2) DESPESAS,  
    ARREDONDAR(DIVIDE(C.DESPCAIXA*((CI.QUANTIDADE * CI.VALORUNIT) - NVL(CI.DESCITEM,0) ),
      SUM((CI.QUANTIDADE * CI.VALORUNIT) - NVL(CI.DESCITEM,0)) OVER (PARTITION BY CI.IDCARRINHO)),2) DESPCAIXA, 
    CASE I.TIPO
      WHEN '09' THEN 0
      ELSE ARREDONDAR(
        DIVIDE(C.TAXAFRETE *((CI.QUANTIDADE * CI.VALORUNIT - NVL(CI.DESCITEM,0)) ),
               SUM(DECODE(I.TIPO,'09',0,(CI.QUANTIDADE * CI.VALORUNIT) - NVL(CI.DESCITEM,0))) OVER (PARTITION BY CI.IDCARRINHO)
        ),2)
    END FRETE,
    IP.MARGEMVENDA
FROM CARRINHOITEM CI
 LEFT JOIN CARRINHO C ON C.IDCARRINHO = CI.IDCARRINHO
 LEFT JOIN FILIAL FI ON (FI.ESTAB = CI.ESTAB)
 INNER JOIN ITEMESTAB IE ON IE.ESTAB = CI.ESTAB AND IE.ESTABITEM = CI.ESTABITEM  AND IE.IDITEM = CI.IDITEM
LEFT JOIN ITEM I ON (I.ESTAB = IE.ESTABITEM) AND (I.IDITEM = IE.IDITEM)
LEFT JOIN FILIALCONFCAD F ON (F.ESTAB = CI.ESTAB)
LEFT JOIN FILIALCONFVDA FV ON (FV.ESTAB = CI.ESTAB)
LEFT JOIN ITEMPRVDA IP ON (IP.IDBANDEIRA = F.IDBANPRECO) AND (IP.ESTAB = IE.ESTABITEM) AND (IP.IDITEM = IE.IDITEM)
WHERE CI.ESTAB = :ESTAB 
AND CI.IDCARRINHO = :IDCARRINHO 
