SELECT
  Y.IDPESS,
  P.NOME,
  Y.LIMITE,
  Y.LIMITEMENSAL,
  Y.LIMITECHEQREC,
  Y.LIMITECP,
  Y.DTPROXREAVAL,
  Y.SALDODUPREC + Y.SALDOCHEQREC + Y.SALDOCHEQCOMP + Y.SALDOCHEQDEV AS SALDOTOTALPEND,
  (Y.LIMITE - (Y.SALDODUPREC + Y.SALDOCHEQREC + Y.SALDOCHEQCOMP + Y.SALDOCHEQDEV)) LIMITEDISPONIVEL
FROM (  
  SELECT
    X.IDPESS,
    P.LIMITE,
    P.LIMITEMENSAL,
    P.LIMITECHEQREC,
    COALESCE(P.LIMITECP,0) AS LIMITECP,
    P.DTPROXREAVAL,
    SUM(X.VLRDUP)  AS VLRDUP,
    SUM(X.DESCDUP) AS DESCDUP,
    SUM(X.SDODUPA)   AS SDODUPA,                                
    SUM(X.SALDODUPREC) AS SALDODUPREC,
    SUM(X.SALDODUPPAG) AS SALDODUPPAG,
    SUM(X.SALDOCHEQREC) AS SALDOCHEQREC,
    SUM(X.SALDOCHEQDEV) AS SALDOCHEQDEV,
    SUM(X.SALDOCHEQCOMP) AS SALDOCHEQCOMP,
    SUM(X.SALDOCHEQEMI) AS SALDOCHEQEMI,
    SUM(X.SALDOCHEQBLOQ) AS SALDOCHEQBLOQ
  FROM (
    
    WITH PESSOAS AS ( SELECT IDPESS FROM PESSOADOC WHERE 0=0 AND IDPESS = :IDPESS )
    
    SELECT 
      FL.ESTAB, 
      P.IDPESS,
      F.VLRDUP,
      F.DESCDUP,      
      0 AS SDODUPA,
      0 AS SALDODUPREC,
      0 AS SALDODUPPAG,
      0 AS SALDOCHEQREC,
      0 AS SALDOCHEQDEV,
      0 AS SALDOCHEQCOMP,
      0 AS SALDOCHEQEMI,
      0 AS SALDOCHEQBLOQ
    FROM PESSOADOCMCP P
    INNER JOIN PESSOAS ON PESSOAS.IDPESS=P.IDPESS
    LEFT JOIN FILIAL FL ON FL.EMPRESA=P.EMPRESA
    LEFT JOIN PESSOAHISFIN F ON F.IDPESS=P.IDPESS AND F.ESTAB=FL.ESTAB    
    WHERE ( ( ','||CAST(:ESTAB AS VARCHAR(1000))||',' LIKE '%,'||FL.ESTAB||',%') OR ( COALESCE(CAST(:ESTAB AS VARCHAR(1000)), ' ')=' ' ) )
    
    UNION ALL
    
    SELECT      
      DUPREC.ESTAB,
      DUPREC.IDPESS,
      SUM(DUPREC.VALOR) AS VLRDUP,
      SUM(COALESCE(DUPREC.DESCONTO,0) + COALESCE(DUPREC.DESCPEND,0)) AS DESCDUP,      
      ARREDONDAR(SUM(
        CASE WHEN TRUNC(DUPREC.DTVENCTO) < TRUNC(SYSDATE) THEN     
          COALESCE(BX.SALDO,0)
        ELSE 0
        END), 2) SDODUPA,
      0 AS SALDODUPREC,
      0 AS SALDODUPPAG,
      0 AS SALDOCHEQREC,
      0 AS SALDOCHEQDEV,
      0 AS SALDOCHEQCOMP,
      0 AS SALDOCHEQEMI,
      0 AS SALDOCHEQBLOQ 
    FROM DUPREC
    INNER JOIN PESSOAS ON (PESSOAS.IDPESS=DUPREC.IDPESS)
    INNER JOIN TABLE(BAIXASDUPREC(DUPREC.ESTAB, DUPREC.IDDUPREC, NULL)) BX ON (0=0)
    LEFT JOIN PORTADOR P ON P.ESTAB=DUPREC.ESTAB AND P.IDPORTADOR=DUPREC.IDPORTADOR
    LEFT JOIN SITUACAO S ON S.IDSITUACAO=DUPREC.IDSITUACAO
    WHERE ( ( ','||CAST(:ESTAB AS VARCHAR(1000))||',' LIKE '%,' || DUPREC.ESTAB || ',%') OR ( COALESCE(CAST(:ESTAB AS VARCHAR(1000)), ' ')=' ' ) )
      AND COALESCE(DUPREC.QUITADA,'N')='N' 
      AND COALESCE(P.LISTAFICHAFIN,'S')='S'
    GROUP BY DUPREC.ESTAB, DUPREC.IDPESS, 0
    
    UNION ALL
    
    SELECT
      C.ESTAB,
      C.IDPESS,
      C.VALOR - H.VALORBX VLRDUP,
      0 DESCDUP,
      0 AS SDODUPA,
      0 AS SALDODUPREC,
      0 AS SALDODUPPAG,
      0 AS SALDOCHEQREC,
      CASE WHEN H.SITUACAO IN ('D','T') THEN C.VALOR - H.VALORBX ELSE 0 END SALDOCHEQDEV,
      CASE WHEN H.SITUACAO IN ('C', 'U') THEN C.VALOR ELSE 0 END SALDOCHEQCOMP,
      0 AS SALDOCHEQEMI,
      0 AS SALDOCHEQBLOQ
    FROM CHEQREC C
    INNER JOIN PESSOAS ON PESSOAS.IDPESS=C.IDPESS
    INNER JOIN TABLE(GETCHEQRECHIST(C.ESTAB, C.IDCHEQREC)) H ON 0=0
    LEFT JOIN PORTADOR P ON P.ESTAB=C.ESTAB AND P.IDPORTADOR=C.IDPORTADOR
    LEFT JOIN ACERFIN A ON (A.ESTAB=C.ESTAB) AND (A.IDACERFIN=C.IDACERFIN)       
    WHERE ( ( ','||CAST(:ESTAB AS VARCHAR(1000))||',' LIKE '%,'||C.ESTAB||',%') OR ( COALESCE(CAST(:ESTAB AS VARCHAR(1000)), ' ')=' ' ) )
       AND COALESCE(P.LISTAFICHAFIN, 'S')='S'    
    
    UNION ALL
    
    SELECT  
      DP.ESTAB,
      DP.IDPESS,
      DP.VALOR AS VLRDUP,
      0 AS DESCDUP,
      0 AS SDODUPA,
      BX.SALDO AS SALDODUPREC,
      0 AS SALDODUPPAG,
      0 AS SALDOCHEQREC,
      0 AS SALDOCHEQDEV,
      0 AS SALDOCHEQCOMP,
      0 AS SALDOCHEQEMI,
      0 AS SALDOCHEQBLOQ
    FROM DUPREC DP
    INNER JOIN PESSOAS ON PESSOAS.IDPESS=DP.IDPESS
    INNER JOIN TABLE(BAIXASDUPREC(DP.ESTAB, DP.IDDUPREC, NULL)) BX ON (0=0)
    LEFT JOIN PORTADOR P ON P.ESTAB=DP.ESTAB AND P.IDPORTADOR=DP.IDPORTADOR
    LEFT JOIN SITUACAO S ON S.IDSITUACAO=DP.IDSITUACAO
    WHERE ( ( ','||CAST(:ESTAB AS VARCHAR(1000))||',' LIKE '%,'||DP.ESTAB||',%') OR ( COALESCE(CAST(:ESTAB AS VARCHAR(1000)), ' ')=' ' ) )   
      AND (COALESCE(DP.QUITADA,'N')='N')
      AND COALESCE(P.LISTAFICHAFIN,'S')='S'
      
    UNION ALL
    
    SELECT  
      DP.ESTAB,
      DP.IDPESS,
      DP.VALOR AS VLRDUP,
      0 AS DESCDUP,
      0 AS SDODUPA,
      0 AS SALDODUPREC,
      (COALESCE(DP.VALOR,0) + COALESCE(DP.JUROSPEND,0) -
      COALESCE(DP.DESCPEND,0) - BX.VALREC) AS SALDODUPPAG,
      0 AS SALDOCHEQREC,
      0 AS SALDOCHEQDEV,
      0 AS SALDOCHEQCOMP,
      0 AS SALDOCHEQEMI,
      0 AS SALDOCHEQBLOQ
    FROM DUPPAG DP
    INNER JOIN PESSOAS ON PESSOAS.IDPESS=DP.IDPESS
    INNER JOIN TABLE(BAIXASDUPPAG(DP.ESTAB, DP.IDDUPPAG, NULL)) BX ON (0=0)
    LEFT JOIN PORTADOR P ON P.ESTAB=DP.ESTAB AND P.IDPORTADOR=DP.IDPORTADOR
    LEFT JOIN SITUACAO S ON S.IDSITUACAO=DP.IDSITUACAO
    WHERE ( ( ','||CAST(:ESTAB AS VARCHAR(1000))||',' LIKE '%,'||DP.ESTAB||',%') OR ( COALESCE(CAST(:ESTAB AS VARCHAR(1000)), ' ')=' ' ) )   
      AND COALESCE(DP.QUITADA,'N')='N'
      AND COALESCE(P.LISTAFICHAFIN,'S')='S'
      AND NOT EXISTS(
                      SELECT 0 FROM ACERDPA AD
                      INNER JOIN NOTAACERFIN NT ON NT.ESTAB=AD.ESTABBX AND NT.IDACERFIN=AD.IDACERFIN
                      INNER JOIN NOTA N ON N.ESTAB=NT.ESTAB AND N.IDNOTA=NT.IDNOTA
                      INNER JOIN NOTACONF NC ON NC.ESTAB=N.ESTABNOTACONF AND NC.IDNOTACONF=N.IDNOTACONF
                      WHERE AD.ESTAB=DP.ESTAB
                        AND AD.IDDUPPAG=DP.IDDUPPAG
                        AND CASE 
                              WHEN N.MOSTRACAIXA=1 THEN 'S'
                              WHEN NC.EMITENFE='N' AND N.SITUACAO=5 THEN 'N'
                              WHEN NC.EMITENFE='S' AND COALESCE(N.EMITENFE,'0') IN ('2','5','9') THEN 'N'
                              WHEN NC.EMITENFE='S' AND N.SITUACAO=10 THEN 'N'
                              ELSE 'S'
                            END='S' )

    UNION ALL
    
    SELECT
      CR.ESTAB,
      CR.IDPESS,
      CR.VALOR VLRDUP,
      0 DESCDUP,
      0 AS SDODUPA,
      0 AS SALDODUPREC,
      0 AS SALDODUPPAG,
      COALESCE(CR.VALOR - H.VALORBX,0) AS SALDOCHEQREC,
      0 AS SALDOCHEQDEV,               
      0 AS SALDOCHEQCOMP,
      0 AS SALDOCHEQEMI,
      0 AS SALDOCHEQBLOQ
    FROM CHEQREC CR
    INNER JOIN PESSOAS ON PESSOAS.IDPESS=CR.IDPESS
    INNER JOIN TABLE(GETCHEQRECHIST(CR.ESTAB, CR.IDCHEQREC)) H ON 0=0
    LEFT JOIN ACERFIN A ON (A.ESTAB=CR.ESTAB) AND (A.IDACERFIN=CR.IDACERFIN)
    LEFT JOIN PORTADOR P ON P.ESTAB=CR.ESTAB AND P.IDPORTADOR=CR.IDPORTADOR
    WHERE ( ( ','||CAST(:ESTAB AS VARCHAR(1000))||',' LIKE '%,'||CR.ESTAB||',%') OR ( COALESCE(CAST(:ESTAB AS VARCHAR(1000)), ' ')=' ' ) )
      AND H.SITUACAO='A'
      AND COALESCE(P.LISTAFICHAFIN, 'S')='S'
        
    UNION ALL
                                                     
    SELECT
      CR.ESTAB,
      CR.IDPESS,
      CR.VALOR VLRDUP,
      0 DESCDUP,
      0 AS SDODUPA,
      0 AS SALDODUPREC,
      0 AS SALDODUPPAG,
      0 AS SALDOCHEQREC,
      0 AS SALDOCHEQDEV,
      0 AS SALDOCHEQCOMP,
      0 AS SALDOCHEQEMI,
      COALESCE(CR.VALOR,0) AS SALDOCHEQBLOQ
    FROM CHEQREC CR
    INNER JOIN PESSOAS ON PESSOAS.IDPESS=CR.IDPESS
    INNER JOIN TABLE(GETCHEQRECHIST(CR.ESTAB, CR.IDCHEQREC)) H ON 0=0
    LEFT JOIN ACERFIN A ON (A.ESTAB=CR.ESTAB) AND (A.IDACERFIN=CR.IDACERFIN)
    LEFT JOIN PORTADOR P ON P.ESTAB=CR.ESTAB AND P.IDPORTADOR=CR.IDPORTADOR
    WHERE ( ( ','||CAST(:ESTAB AS VARCHAR(1000))||','  LIKE '%,'||CR.ESTAB||',%') OR ( COALESCE(CAST(:ESTAB AS VARCHAR(1000)), ' ')=' ' ) )
      AND CR.BOMPARA > TRUNC(SYSDATE)
      AND CR.DTLIBERADO IS NULL
      AND H.SITUACAO='B'
      AND COALESCE(P.LISTAFICHAFIN,'S')='S'  
        
    UNION ALL
    
    SELECT
      CE.ESTAB,
      CE.IDPESS,
      CE.VALOR VLRDUP,
      0 DESCDUP,
      0 AS SDODUPA,
      0 AS SALDODUPREC,
      0 AS SALDODUPPAG,
      0 AS SALDOCHEQREC,
      0 AS SALDOCHEQDEV, 
      0 AS SALDOCHEQCOMP,
      COALESCE(CE.VALOR,0) AS SALDOCHEQEMI,
      0 AS SALDOCHEQBLOQ
    FROM CHEQEMI CE
    INNER JOIN PESSOAS ON PESSOAS.IDPESS=CE.IDPESS
    LEFT JOIN PORTADOR P ON P.ESTAB=CE.ESTAB AND P.IDPORTADOR=CE.IDPORTADOR
    WHERE ( ( ','||CAST(:ESTAB AS VARCHAR(1000))||',' LIKE '%,'||CE.ESTAB||',%') OR ( COALESCE(CAST(:ESTAB AS VARCHAR(1000)), ' ')=' ' ) )
      AND CE.IDLANFIN IS NULL
      AND COALESCE(P.LISTAFICHAFIN,'S')='S'
  ) X
  LEFT JOIN FILIAL ON FILIAL.ESTAB=X.ESTAB
  INNER JOIN PESSOADOCCREDSCORE P ON P.EMPRESA=FILIAL.EMPRESA AND P.IDPESS=:IDPESS
  GROUP BY X.IDPESS,P.LIMITE, P.LIMITEMENSAL, P.LIMITECP, P.DTPROXREAVAL, P.LIMITECHEQREC
) Y INNER JOIN PESSOADOC P ON P.IDPESS = Y.IDPESS