WITH ITEMSIMILAR AS (
    SELECT 
        CI.ESTAB,
        CI.IDITEM,
        I.DESCRICAO,
        CI.QUANTIDADE,
        CI.VALORUNIT,
        CI.DESCITEM, 
        M.DESCRICAO MARCA,
        IC.IDSIMILAR
    FROM CARRINHOITEM CI
    INNER JOIN ITEMESTAB IE ON IE.ESTAB = CI.ESTAB AND IE.IDITEM = CI.IDITEM
    INNER JOIN ITEM I ON I.ESTAB = IE.ESTABITEM AND I.IDITEM = IE.IDITEM
    INNER JOIN ITEMCATEGORIA IC ON IC.ESTAB = IE.ESTABITEM AND IC.IDITEM = IE.IDITEM
    INNER JOIN TABLE(RETORNAITEMPRECO(IE.ESTAB, IE.IDITEM, 0, 'S', 0)) P ON (0=0)
    LEFT JOIN MARCA M ON M.IDMARCA = IC.IDMARCA
    WHERE CI.ESTAB = :ESTAB
      AND CI.IDCARRINHO = :IDCARRINHO
)
SELECT
    X.*
FROM (
SELECT
    ITEMSIMILAR.IDITEM AS IDITEMORIGEM,
    ITEMSIMILAR.DESCRICAO AS DESCRICAOITEMORIGEM,
    ITEMSIMILAR.QUANTIDADE  AS QUANTIDADEITEMORIGEM,
    ITEMSIMILAR.VALORUNIT AS VALORUNITITEMORIGEM,
    ITEMSIMILAR.DESCITEM AS DESCITEMITEMORIGEM,
    ITEMSIMILAR.MARCA AS MARCAITEMORIGEM,
    ITEM.IDITEM,
    ITEM.DESCRICAO,
    COALESCE(
      ( SELECT
          COALESCE(ESTOQUEFISCAL.QUANTIDADE,0)
        FROM ESTOQUEFISCAL
          WHERE (ESTOQUEFISCAL.ESTAB = ITEMESTAB.ESTAB)
            AND (ESTOQUEFISCAL.IDITEM = ITEMESTAB.IDITEM)
            AND (ESTOQUEFISCAL.DATA = (SELECT MAX(E2.DATA) FROM ESTOQUEFISCAL E2
                                       WHERE E2.ESTAB = ESTOQUEFISCAL.ESTAB
                                         AND E2.IDITEM = ESTOQUEFISCAL.IDITEM) )),0) AS SDOATUAL,
    DECODE(COALESCE(P.PRECO2,0),0, P.PRECO, P.PRECO2) AS PRECO,
    DECODE(COALESCE(P.PRECO2,0), 0, 0, COALESCE(P.PRECO,0))  AS OFERTA,
    MARCA.DESCRICAO MARCA
FROM ITEMESTAB 
 INNER JOIN ITEM ON ITEM.ESTAB = ITEMESTAB.ESTABITEM AND ITEM.IDITEM = ITEMESTAB.IDITEM
 INNER JOIN ITEMSIMILAR ON ITEMSIMILAR.ESTAB = ITEMESTAB.ESTAB
 INNER JOIN ITEMCATEGORIA ON ITEMCATEGORIA.ESTAB = ITEM.ESTAB AND ITEMCATEGORIA.IDSIMILAR = ITEMSIMILAR.IDSIMILAR AND ITEMCATEGORIA.IDITEM = ITEMESTAB.IDITEM
 LEFT JOIN ESTOQUELOCAL ON ESTOQUELOCAL.ESTAB = ITEMESTAB.ESTAB AND ESTOQUELOCAL.IDESTOQUELOCAL = ITEMESTAB.IDESTOQUELOCAL  
 INNER JOIN TABLE(RETORNAITEMPRECO(ITEMESTAB.ESTAB, ITEMESTAB.IDITEM, 0, 'S', 0)) P ON (0=0)
 LEFT JOIN ITEMREPOSICAO  ON ITEMREPOSICAO.ESTAB = ITEMESTAB.ESTAB AND ITEMREPOSICAO.ESTABITEM = ITEMESTAB.ESTABITEM AND ITEMREPOSICAO.IDITEM = ITEMESTAB.IDITEM
 LEFT JOIN MARCA ON MARCA.IDMARCA = ITEMCATEGORIA.IDMARCA
 WHERE (ITEMREPOSICAO.INATIVO NOT IN ('S','A','T') OR ITEMREPOSICAO.INATIVO IS NULL )
  AND (ITEM.TINTA <> 'P' OR ITEM.TINTA IS NULL)
  AND (ITEM.ITEMVDAIND = 'S' OR ITEM.ITEMVDAIND IS NULL) 
  AND (ITEMESTAB.USAMIX = 'S')
) X 
WHERE X.IDITEMORIGEM <> X.IDITEM
  AND X.SDOATUAL > 0