WITH CARRINHOINFO AS(
    SELECT
        CI.ESTAB,
        CI.ESTABITEM,
        CI.ESTABBX,
        CI.IDCARRINHO,
        CI.IDITEM,
        I.DESCRICAO,
        CI.IDLOCALRETIRADA,
        CI.IDTABPRVDA
    FROM CARRINHOITEM CI
    INNER JOIN ITEM I ON I.ESTAB = CI.ESTABITEM AND I.IDITEM = CI.IDITEM
    WHERE CI.ESTAB = :ESTAB
      AND CI.IDCARRINHO = :IDCARRINHO
)

SELECT
    CI.IDITEM  || ' - ' || CI.DESCRICAO AS ITEMCARRINHO,
    ITEM.IDITEM ||' - '||  ITEM.DESCRICAO  AS ITEMAGREGADO,
    COALESCE(SUM(E.SALDO),0) SDOATUAL,
    DECODE(COALESCE(P.PRECO2,0),0, P.PRECO, P.PRECO2) AS PRECO,
  DECODE(COALESCE(P.PRECO2,0), 0, 0, COALESCE(P.PRECO,0))  AS OFERTA
FROM ITEMAGREGADOS IA
  INNER JOIN CARRINHOINFO CI ON CI.ESTAB = IA.ESTAB AND CI.IDITEM = IA.IDITEM
  INNER JOIN ITEMESTAB IE ON IE.ESTABITEM = IA.ESTAB AND IE.IDITEM = IA.IDAGREGADO AND IE.USAMIX = 'S'
  INNER JOIN TABLE(RETORNAITEMPRECO(IE.ESTAB, IE.IDITEM, 0, 'S', 0)) P ON (0=0)
  LEFT JOIN ITEM ON ITEM.ESTAB  = IE.ESTABITEM AND ITEM.IDITEM = IE.IDITEM
  LEFT JOIN ESTOQUESALDO E ON E.ESTAB = IE.ESTAB AND E.ESTABITEM = IE.ESTABITEM AND E.IDITEM = IE.IDITEM AND E.IDESTOQUETIPO = 1
GROUP BY CI.IDITEM, CI.DESCRICAO, ITEM.IDITEM, ITEM.DESCRICAO, P.PRECO, P.PRECO2