WITH CARRINHOINFO AS(
    SELECT
        CI.ESTAB,
        CI.ESTABITEM,
        CI.ESTABBX,
        CI.IDCARRINHO,
        CI.IDITEM,
        I.DESCRICAO,
        CI.IDLOCALRETIRADA,
        CI.IDTABPRVDA
    FROM CARRINHOITEM CI
    INNER JOIN ITEM I ON I.ESTAB = CI.ESTABITEM AND I.IDITEM = CI.IDITEM
    WHERE CI.ESTAB = :ESTAB
      AND CI.IDCARRINHO = :IDCARRINHO
)

SELECT
    CI.IDITEM  || ' - ' || CI.DESCRICAO AS ITEMCARRINHO,
    AR.IDITEMREL||'-'||I.DESCRICAO PRODUTORECORRENTE,
    (SELECT M.DESCRICAO FROM MARCA M WHERE M.IDMARCA = IC.IDMARCA) MARCA,
    ROUND(AR.QTDVENDIDA /  A.QTDVENDIDA, 2) * 100 PERC,
    ROW_NUMBER() OVER(ORDER BY ROUND(AR.QTDVENDIDA /  A.QTDVENDIDA, 2) DESC) ORDEM,
    GETSALDOITEMCARRLOCALRETSIMP(IR.ESTAB, IR.IDITEM,                      
    COALESCE(IR.IDLOCALRETIRADA, TO_NUMBER(CI.IDLOCALRETIRADA)), COALESCE(IR.ESTABLOCALRET, TO_NUMBER(CI.ESTABBX))
  ) SALDO,
  I.UNIDADE, 
  CASE COALESCE(PRECOS.PRECO2,0)                      
    WHEN 0 THEN COALESCE(PRECOS.PRECO,0) 
    ELSE COALESCE(PRECOS.PRECO2,0)                
  END PRECONORMAL,
  CASE                                                                                                                             
    WHEN (COALESCE(PRECOS.PRECO2,0) <> COALESCE(PRECOS.PRECO,0)) THEN 
      COALESCE(PRECOS.PRECO,0)                                
    ELSE 0 
  END AS PRECOPROMO
FROM ANALISEQTDVDA A                                    
 INNER JOIN ANALISEQTDVDAREL AR ON AR.ESTABITEM = A.ESTABITEM AND AR.IDITEM = A.IDITEM
 INNER JOIN CARRINHOINFO CI ON A.ESTABITEM = CI.ESTABITEM AND A.IDITEM = CI.IDITEM
 INNER JOIN TABLE(PKG_PRECOS.RETORNAITEMPRECO(CI.ESTAB, AR.IDITEMREL, I_IDPESS => 0, I_OPER=>'S', I_IDNOTACONF=>0)) PRECOS ON 0=0
 INNER JOIN ITEMREPOSICAO IR ON IR.ESTAB = CI.ESTAB AND IR.ESTABITEM = CI.ESTABITEM AND IR.IDITEM = AR.IDITEMREL
 LEFT JOIN ITEM I ON I.ESTAB = AR.ESTABITEM AND I.IDITEM = AR.IDITEMREL
 LEFT JOIN ITEMCATEGORIA IC ON IC.ESTAB = I.ESTAB AND IC.IDITEM = I.IDITEM