SELECT
  N.ESTAB,
  F.RAZAOSOC,
  N.EMISSAO,
  N.ENTRADASAIDA,
  N.ESPECIE,
  N.IDNOTA,
  N.NUMDOC,
  N.OPERACAO,
  N.SERIE,
  DECODE(N.SITUACAO,
  '1', 'Sem Acerto Financeiro',
  '2', 'Importada de XML',
  '3', 'Entrega de Pedido e Sem Acerto Financeiro',
  '4', 'Em Digitação',
  '5', 'Conferida',
  '6', 'Cancelada',
  '7', 'Ajuste Estoque',
  '8', 'Conferida e Enviada a Receita',
  '9', 'Conferida e Enviada a Receita com Erros',
  'Conferida e Autorizada')SITUACAO,
  COALESCE(N.MOTIVODEV,NP.MOTIVODEV,'SEM MOTIVO INFORMADO') AS MOTIVODEV,
  NOTA_PAGAMENTOS(N.ESTAB,N.IDNOTA) AS PAGAMENTO, 
  TIPOOPER.DESCRICAO AS TIPOOPER,
  NI.IDITEM ,
  I.DESCRICAO,
  NI.QUANTIDADE,
  NI.VUNITARIO,
  COALESCE(NI.DESCITEM,0) DESCITEM,
  (COALESCE(NI.VUNITARIO,0) * COALESCE(NI.QUANTIDADE,0) ) - COALESCE(NI.DESCITEM,0) AS TOTAL,
  DP.IDDEPTO || ' - ' || DP.DESCRICAO AS DEPARTAMENTO,
  SC.IDSECAO || ' - ' || SC.DESCRICAO AS SECAO,
  GI.IDGRUPOITEM || ' - ' || GI.DESCRICAO AS GRUPO,
  SG.IDSUBGRUPO || ' - ' || SG.DESCRICAO AS SUBGRUPO
FROM NOTAITEM NI
  INNER JOIN ITEM I ON I.ESTAB = NI.ESTABITEM AND I.IDITEM = NI.IDITEM
  INNER JOIN ITEMESTAB IE ON IE.ESTAB = NI.ESTAB AND IE.ESTABITEM = I.ESTAB AND IE.IDITEM = I.IDITEM
  INNER JOIN ITEMCATEGORIA IC ON IC.ESTAB = IE.ESTAB AND IC.IDITEM = IE.IDITEM
  INNER JOIN DEPARTAMENTO DP ON DP.IDDEPTO = IC.IDDEPTO
  INNER JOIN SECAO SC ON SC.IDSECAO = IC.IDSECAO
  INNER JOIN GRUPOITEM GI ON GI.IDGRUPOITEM = IC.IDGRUPOITEM
  INNER JOIN SUBGRUPO SG ON SG.IDSUBGRUPO = IC.IDSUBGRUPO
  INNER JOIN NOTA N ON NI.ESTAB = N.ESTAB AND NI.IDNOTA = N.IDNOTA    
  INNER JOIN FILIAL F ON N.ESTAB = F.ESTAB
  LEFT JOIN NOTAMCP NP ON NP.ESTAB = N.ESTAB AND NP.IDNOTA = N.IDNOTA
  LEFT JOIN TIPOOPER ON TIPOOPER.IDTIPOOPER = N.IDTIPOOPER
  LEFT JOIN NOTAITEMCP NM ON NM.ESTAB = NI.ESTAB AND NM.IDNOTA = NI.IDNOTA AND NM.SEQITEM = NI.SEQITEM
WHERE ( ( (','||CAST(:ESTAB AS VARCHAR(1000)) ||',')  LIKE '%,' || N.ESTAB || ',%') OR
                  ( (COALESCE(CAST(:ESTAB AS VARCHAR(1000)), ' ') = ' ') ) )
  AND N.IDPESS = :IDPESS
  AND TRUNC(N.EMISSAO) < (SYSDATE - 365)
  AND N.IDTIPOOPER IN ('DV')               
ORDER BY N.EMISSAO DESC