SELECT
    P.IDPESS,
    P.NOME,
    P.CNPJF,
    DECODE(PE.TIPOEND,
      'E', 'Padrão de Entrega',
      'C', 'Cobrança',
      'Principal') AS TIPOEND,
    E.ENDERECO,
    E.COMPLEMENTO,
    E.NUMEND,
    E.BAIRRO,
    C.NOME AS CIDADE,
    E.CEP,
    E.TELEFONE,
    E.CELULAR,
    P.EMAIL,
    PM.DTCADASTRO
FROM PESSOADOCEND PE
INNER JOIN PESSOADOC P ON P.IDPESS = PE.IDPESS
INNER JOIN ENDERECO E ON E.IDEND = PE.IDEND
INNER JOIN CIDADE C ON C.CIDADE = E.CIDADE
INNER JOIN PESSOADOCMCP PM ON PM.IDPESS = P.IDPESS
WHERE (0=0)
  AND PE.TIPOEND IN ('P','C','E')
  AND P.IDPESS = :IDPESS